PYTHON ?= $(shell for candidate in python3 python; do if $$candidate -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 9) else 1)' >/dev/null 2>&1; then command -v $$candidate; break; fi; done)
ARGS ?=
HUB ?=
VENV ?= .venv
LOCAL_BIN ?= $(HOME)/.local/bin
# Console scripts declared in pyproject.toml [project.scripts]; keep in sync.
CONSOLE_SCRIPTS = mac mac-hermes mac-agent mac-firecrawl-gateway mac-hermes-gateway

.PHONY: require-python install-hooks setup deploy test test-api test-cli test-ui build publish link-cli

require-python:
	@if [ -z "$(PYTHON)" ]; then \
		echo "Python 3.9+ is required (python3 or python)"; \
		exit 127; \
	fi

install-hooks:
	cp -f scripts/pre-push .git/hooks/pre-push
	chmod +x .git/hooks/pre-push
	@echo "pre-push hook installed"

setup: require-python
	$(PYTHON) setup.py $(ARGS)

deploy: require-python
	@if [ -z "$(HUB)" ] && ! printf '%s\n' "$(ARGS)" | grep -Eq -- '(^|[[:space:]])--(hub|new-hub)(=|[[:space:]]|$$)'; then \
		echo "usage: make deploy HUB=<hub-node> [ARGS='agent-a ...']"; \
		echo "   or: make deploy ARGS='--new-hub <hub-node> --target user@host[:port]'"; \
		exit 2; \
	fi
	$(PYTHON) setup.py $(if $(HUB),--hub $(HUB),) $(ARGS)

test:
	uv run --extra dev pytest -q

test-api:
	uv run --extra dev pytest -q -m api tests/

test-cli:
	uv run --extra dev pytest -q -m cli tests/

test-ui:
	uv run --extra dev pytest -q -m ui tests/

# Build the distributable wheel into dist/ (numpy + all runtime deps pinned in
# pyproject.toml come along for any node that pip-installs it).
build: require-python
	rm -rf dist
	uv build --wheel
	@ls -1 dist/*.whl

# User-visible "publish" action: build the wheel and verify its console-script
# entry points are intact, leaving dist/*.whl ready to install on fleet nodes.
publish: build
	@whl=$$(ls dist/mac-*.whl); \
	echo "verifying entry points in $$whl ..."; \
	if unzip -p "$$whl" 'mac-*.dist-info/entry_points.txt' 2>/dev/null | grep -q '^mac = mac.cli:main'; then \
		echo "  ok: mac console script present"; \
	else \
		echo "  ERROR: mac console script missing from wheel" >&2; exit 1; \
	fi; \
	echo "published $$whl"; \
	echo "  this machine:  make link-cli                              # symlink venv scripts onto PATH"; \
	echo "  fleet node:    scp $$whl <node>: && <node-venv>/bin/pip install --reinstall $$whl"

# Put the mac CLIs on PATH by symlinking the venv's console scripts into
# ~/.local/bin (the entry points are generated by an editable/wheel install).
link-cli:
	@mkdir -p "$(LOCAL_BIN)"
	@linked=0; for s in $(CONSOLE_SCRIPTS); do \
		if [ -x "$(VENV)/bin/$$s" ]; then \
			ln -sf "$(abspath $(VENV))/bin/$$s" "$(LOCAL_BIN)/$$s" && echo "  linked $(LOCAL_BIN)/$$s"; \
			linked=$$((linked+1)); \
		fi; \
	done; \
	if [ "$$linked" = 0 ]; then \
		echo "  no console scripts in $(VENV)/bin — run 'uv sync' (or pip install -e .) first" >&2; exit 1; \
	fi
	@case ":$$PATH:" in *":$(LOCAL_BIN):"*) ;; *) echo "  NOTE: add $(LOCAL_BIN) to PATH (e.g. in ~/.bashrc)";; esac
