PYTHON ?= $(shell for candidate in "$(VENV)/bin/python" python3.11 python3 python; do if $$candidate -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' >/dev/null 2>&1; then command -v $$candidate || printf '%s\n' "$$candidate"; break; fi; done)
ARGS ?=
HUB ?=
VENV ?= .venv
LOCAL_BIN ?= $(HOME)/.local/bin
NPM ?= npm
IDE_DIR ?= ide
IDE_API_URL ?=
IDE_HOST ?= 127.0.0.1
IDE_PORT ?= 5273
IDE_PACKAGE ?= dist/mac-ide-web.tar.gz
# Console scripts declared in pyproject.toml [project.scripts]; keep in sync.
CONSOLE_SCRIPTS = mac mac-hermes mac-agent mac-firecrawl-gateway mac-k8s-orchestrator mac-k8s-bootstrap mac-task-runner mac-webdav-server mac-evidence mac-hermes-gateway

.PHONY: require-python install-hooks setup deploy test coverage test-api test-cli test-ui cli-coverage ide-install ide-run ide-dev ide-check ide-build ide-preview ide-package desktop-install desktop-check desktop-package desktop-dist build publish link-cli

require-python:
	@if [ -z "$(PYTHON)" ]; then \
			echo "Python 3.11+ is required ($(VENV)/bin/python, python3.11, python3, or python)"; \
		exit 127; \
	fi

install-hooks:
	cp -f scripts/pre-push .git/hooks/pre-push
	chmod +x .git/hooks/pre-push
	@echo "pre-push hook installed"

setup: require-python
	$(PYTHON) setup.py $(ARGS)

deploy: require-python
	@if [ -z "$(HUB)" ] && ! printf '%s\n' "$(ARGS)" | grep -Eq -- '(^|[[:space:]])--(hub|new-hub)(=|[[:space:]]|$$)'; then \
		echo "usage: make deploy HUB=<hub-node> [ARGS='agent-a ...']"; \
		echo "   or: make deploy ARGS='--new-hub <hub-node> --target user@host[:port]'"; \
		exit 2; \
	fi
	$(PYTHON) setup.py $(if $(HUB),--hub $(HUB),) $(ARGS)

test:
	uv run --extra dev coverage run -m pytest -q
	uv run --extra dev coverage report

coverage:
	uv run --extra dev coverage run -m pytest
	uv run --extra dev coverage report

test-api:
	uv run --extra dev pytest -q -m api tests/

test-cli:
	uv run --extra dev pytest -q -m cli tests/

test-ui:
	uv run --extra dev pytest -q -m ui tests/

# Print CLI subcommand coverage ratio: (tested / total) * 100.
# Uses the same discovery logic as tests/cli/test_cli_coverage_gate.py.
cli-coverage:
	@$(VENV)/bin/python scripts/cli-coverage.py

ide-install:
	cd $(IDE_DIR) && $(NPM) ci

ide-run ide-dev:
	cd $(IDE_DIR) && MAC_API_URL="$(IDE_API_URL)" $(NPM) run dev -- --host $(IDE_HOST) --port $(IDE_PORT)

ide-check:
	cd $(IDE_DIR) && $(NPM) run typecheck

ide-build:
	cd $(IDE_DIR) && $(NPM) run build

ide-preview: ide-build
	cd $(IDE_DIR) && $(NPM) run preview -- --host $(IDE_HOST) --port $(IDE_PORT)

ide-package: ide-build
	mkdir -p "$$(dirname "$(IDE_PACKAGE)")"
	tar -czf "$(IDE_PACKAGE)" -C "$(IDE_DIR)/dist" .
	@echo "packaged IDE web bundle: $(IDE_PACKAGE)"

desktop-install:
	cd desktop && npm ci

desktop-check:
	cd desktop && npm run check

desktop-package:
	cd desktop && npm run package

desktop-dist:
	cd desktop && npm run dist

# Build the distributable wheel into dist/ (numpy + all runtime deps pinned in
# pyproject.toml come along for any node that pip-installs it).
build: require-python
	rm -rf dist
	uv build --wheel
	@ls -1 dist/*.whl

# User-visible "publish" action: build the wheel and verify its console-script
# entry points are intact, leaving dist/*.whl ready to install on fleet nodes.
publish: build
	@whl=$$(ls dist/mac-*.whl); \
	echo "verifying entry points in $$whl ..."; \
	entries=$$(unzip -p "$$whl" 'mac-*.dist-info/entry_points.txt' 2>/dev/null); \
	for s in $(CONSOLE_SCRIPTS); do \
		if printf '%s\n' "$$entries" | grep -q "^$$s = "; then \
			echo "  ok: $$s console script present"; \
		else \
			echo "  ERROR: $$s console script missing from wheel" >&2; exit 1; \
		fi; \
	done; \
	echo "published $$whl"; \
	echo "  this machine:  make link-cli                              # symlink venv scripts onto PATH"; \
	echo "  fleet node:    scp $$whl <node>: && <node-venv>/bin/pip install --reinstall $$whl"

# Put the mac CLIs on PATH by symlinking the venv's console scripts into
# ~/.local/bin (the entry points are generated by an editable/wheel install).
link-cli:
	@mkdir -p "$(LOCAL_BIN)"
	@linked=0; for s in $(CONSOLE_SCRIPTS); do \
		if [ -x "$(VENV)/bin/$$s" ]; then \
			ln -sf "$(abspath $(VENV))/bin/$$s" "$(LOCAL_BIN)/$$s" && echo "  linked $(LOCAL_BIN)/$$s"; \
			linked=$$((linked+1)); \
		fi; \
	done; \
	if [ "$$linked" = 0 ]; then \
		echo "  no console scripts in $(VENV)/bin — run 'uv sync' (or pip install -e .) first" >&2; exit 1; \
	fi
	@case ":$$PATH:" in *":$(LOCAL_BIN):"*) ;; *) echo "  NOTE: add $(LOCAL_BIN) to PATH (e.g. in ~/.bashrc)";; esac
