"""Generated-artifact guards must ride along with every focused test run.

On 2026-08-07 main was red across three consecutive commits (71bc68b8,
05e933ee, f717ebe8) and every one of those pull requests had been green. The
failure was ``stale generated environment registry`` -- adding
``MAC_DEPLOY_CONTAINER_RUNTIME_PATHS`` to a SHELL script staled a registry that
is generated by scanning the tree.

The pull-request gate could not have caught it. ``sanity`` runs an
impact-selected subset, and the thing that invalidates a generated artifact is
not a code path the guard covers: nothing links ``deploy/fleet-node-install.sh``
to ``tests/test_env_config.py``, because the guard does not exercise that
script -- it re-derives a registry from the whole tree. Renaming a test
(f717ebe8) staled the committed impact map the same way.

So these guards belong in ``always_run``: unreachable by selection, cheap (47
tests, ~10 seconds), and with the worst failure mode there is -- invisible on
the PR, red on main, where it blocks everyone and is found by whoever merges
next rather than whoever caused it.

Measured against the resolver before and after the policy change, for the exact
shape that broke main (a change to deploy/fleet-node-install.sh alone):

    before   40 tests selected, test_env_config.py NOT among them
    after    43 tests selected, all three guards present
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]

#: Guards whose staleness is invisible to impact selection. Each re-derives a
#: generated artifact from the whole tree, so no single changed file implicates
#: it, and its failure surfaces only after a merge.
GENERATED_ARTIFACT_GUARDS = (
    "tests/test_env_config.py",
    "tests/test_build_test_impact_map.py",
    "tests/test_resolve_impacted_tests.py",
)


def _policy_always_run() -> set[str]:
    try:
        import tomllib
    except ModuleNotFoundError:  # pragma: no cover - Python < 3.11
        import tomli as tomllib  # type: ignore[no-redef]

    with (ROOT / "test-policy.toml").open("rb") as handle:
        policy = tomllib.load(handle)
    for section in policy.values():
        if isinstance(section, dict) and "always_run" in section:
            return set(section["always_run"])
    return set(policy.get("always_run", []))


@pytest.mark.parametrize("guard", GENERATED_ARTIFACT_GUARDS)
def test_the_guard_is_in_always_run(guard):
    """Dropping one restores the PR-green/main-red split it exists to close."""
    assert guard in _policy_always_run(), (
        "%s is no longer in test-policy.toml always_run, so a change that "
        "stales its artifact will pass the pull request and break main" % guard
    )


@pytest.mark.parametrize("guard", GENERATED_ARTIFACT_GUARDS)
def test_the_guard_exists(guard):
    """A policy entry naming a deleted file protects nothing."""
    assert (ROOT / guard).is_file()


def test_a_shell_only_change_selects_the_guards():
    """End to end, on the change that actually broke main.

    Asserting the policy file alone would not prove selection honours it, and
    the policy is not the only input -- the impact map carries its own
    always_run list. This runs the real resolver.
    """
    completed = subprocess.run(
        [
            sys.executable,
            str(ROOT / "scripts" / "resolve-impacted-tests.py"),
            "--changed-file",
            "deploy/fleet-node-install.sh",
            "--tests-only",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=300,
    )
    assert completed.returncode == 0, completed.stderr
    selected = {line.strip() for line in completed.stdout.splitlines() if line.strip()}

    missing = [guard for guard in GENERATED_ARTIFACT_GUARDS if guard not in selected]
    assert not missing, (
        "a shell-only change does not select %s; that is exactly how "
        "MAC_DEPLOY_CONTAINER_RUNTIME_PATHS staled the env registry on a green "
        "pull request and turned main red" % missing
    )
