"""Parsing and file-IO coverage for MAC's dotenv helpers (``mac.deploy_env``)."""

from __future__ import annotations

from mac import deploy_env


def test_env_assignment_parser_fallbacks_and_file_io(tmp_path) -> None:
    assert deploy_env._raw_env_assignment("missing") is None
    assert deploy_env._raw_env_assignment("export KEY=value") == ("KEY", "value")
    assert deploy_env._parse_env_assignment("KEY='unterminated") is None
    assert deploy_env._parse_env_assignment("KEY=value extra") == ("KEY", "value")
    assert deploy_env._parse_env_assignment("export KEY='a b'") == ("KEY", "a b")
    assert deploy_env._parse_env_assignment("export") is None
    assert deploy_env.read_env_file(tmp_path / "missing") == {}
    path = tmp_path / "env"
    deploy_env.write_env_file(path, {"SAFE": "value", "QUOTED": "a b"})
    assert deploy_env.read_env_file(path) == {"SAFE": "value", "QUOTED": "a b"}
    assert path.stat().st_mode & 0o777 == 0o600
    assert path.read_text(encoding="utf-8").startswith("# Generated by mac.\n")


def test_update_env_file_merges_without_dropping_existing_keys(tmp_path) -> None:
    path = tmp_path / "mac.env"
    deploy_env.write_env_file(path, {"KEEP": "1", "CHANGE": "old"})

    merged = deploy_env.update_env_file(path, {"CHANGE": "new", "ADD": 2})

    assert merged == {"KEEP": "1", "CHANGE": "new", "ADD": "2"}
    assert deploy_env.read_env_file(path) == merged
    assert path.stat().st_mode & 0o777 == 0o600


def test_worker_capabilities_retire_openclaw_and_default_when_empty() -> None:
    assert deploy_env.normalize_worker_capabilities("") == deploy_env.DEFAULT_WORKER_CAPABILITIES
    assert deploy_env.normalize_worker_capabilities("ops, openclaw,hermes,ops") == "ops,hermes"
