"""Every Hermes patch must be structurally capable of applying upstream.

`tests/test_hermes_vendor_integrity.py` pins a digest of the vendored tree, so
it catches drift in the OUTPUT. It cannot catch a broken INPUT: for months the
patch set could not be re-applied at all, and nothing failed --

    fts5-orphan-schema-recovery.patch          corrupt patch at line 259
    remove-duplicate-top-level-skills.patch    src/mac/_hermes/tools/skills_sync.py: No such file or directory

`scripts/vendor-hermes-snapshot.sh` runs `git apply` under `set -euo pipefail`,
so the first failure aborted the whole vendor before writing anything. The
documented "reproduces the committed tree byte-for-byte" guarantee -- load
bearing in the Hermes-vs-OpenClaw maintenance-cost comparison -- was false, and
the digest test was the only thing standing between the tree and silent drift.

The true check is a full re-vendor against pristine upstream, which needs a
network clone of a large repository and so does not belong in every build. This
module is the offline half, and it targets the two failure modes actually
observed:

1. **Malformed hunks.** Every `@@ -a,b +c,d @@` header's line counts must match
   the body that follows. A hand-edited diff whose header was not recomputed is
   exactly what "corrupt patch at line 259" means.
2. **Wrong path root.** Patches are applied inside a pristine UPSTREAM checkout,
   where the runtime lives at `tools/skills_sync.py` -- not at
   `src/mac/_hermes/tools/skills_sync.py`. A patch generated by diffing the
   vendored tree carries MAC-repo paths and can never apply.

Neither check needs the upstream source, so both run everywhere.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
_PATCH_DIR = _REPO_ROOT / "deploy" / "hermes"
_VENDORED = _REPO_ROOT / "src" / "mac" / "_hermes"

_HUNK_RE = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")
_PATH_RE = re.compile(r"^(?:---|\+\+\+) (?:[ab]/)?(.+?)(?:\t.*)?$")

#: Paths that legitimately do not exist in the vendored tree: the vendor script
#: prunes these trees, so a patch may touch them upstream without them landing.
_PRUNED_PREFIXES = ("tests/", "docs/", "scripts/", "web/", "website/")


def _patches() -> list[Path]:
    return sorted(_PATCH_DIR.glob("*.patch"))


def test_there_are_patches_to_check():
    """Guard the guard: an empty glob must not read as success."""
    assert _patches(), "no patches found in %s" % _PATCH_DIR


@pytest.mark.parametrize("patch", _patches(), ids=lambda p: p.name)
def test_hunk_headers_match_their_bodies(patch: Path):
    """Catches `git apply: corrupt patch at line N` before a re-vendor does."""
    lines = patch.read_text(encoding="utf-8", errors="replace").splitlines()
    index = 0
    hunks = 0
    while index < len(lines):
        match = _HUNK_RE.match(lines[index])
        if not match:
            index += 1
            continue
        hunks += 1
        header_line = index + 1
        declared_old = int(match.group(2) or 1)
        declared_new = int(match.group(4) or 1)

        actual_old = actual_new = 0
        index += 1
        while index < len(lines):
            line = lines[index]
            if _HUNK_RE.match(line) or line.startswith("diff --git "):
                break
            if line.startswith("\\"):  # "\ No newline at end of file"
                index += 1
                continue
            head = line[:1]
            if head == "-":
                actual_old += 1
            elif head == "+":
                actual_new += 1
            elif head in (" ", ""):
                actual_old += 1
                actual_new += 1
            else:
                break
            index += 1

        assert (actual_old, actual_new) == (declared_old, declared_new), (
            "%s:%d hunk header declares -%d/+%d but its body has -%d/+%d. "
            "git apply will reject this as a corrupt patch. Regenerate the "
            "patch from a real diff rather than editing the @@ header by hand."
            % (
                patch.name,
                header_line,
                declared_old,
                declared_new,
                actual_old,
                actual_new,
            )
        )
    assert hunks, "%s contains no hunks" % patch.name


@pytest.mark.parametrize("patch", _patches(), ids=lambda p: p.name)
def test_paths_are_upstream_relative(patch: Path):
    """Patches apply inside a pristine UPSTREAM checkout, not this repo."""
    offenders = []
    for line in patch.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line.startswith(("--- ", "+++ ")):
            continue
        match = _PATH_RE.match(line)
        if not match:
            continue
        path = match.group(1).strip()
        if path == "/dev/null":
            continue
        if path.startswith("src/mac/_hermes/"):
            offenders.append(path)

    assert not offenders, (
        "%s targets MAC-repo paths %s. The vendor script applies patches inside "
        "a pristine upstream checkout where the runtime is at the tree root "
        "(e.g. 'tools/skills_sync.py', not 'src/mac/_hermes/tools/skills_sync.py'). "
        "This patch was generated by diffing the vendored tree and can never "
        "apply. Regenerate it against upstream."
        % (patch.name, sorted(set(offenders))[:3])
    )


@pytest.mark.parametrize("patch", _patches(), ids=lambda p: p.name)
def test_targets_exist_in_the_vendored_tree(patch: Path):
    """A patch whose target is absent will fail the next re-vendor.

    Skips paths under trees the vendor script prunes, and additions
    (`--- /dev/null`), which have no pre-image.
    """
    text = pytest.importorskip("pathlib") and patch.read_text(
        encoding="utf-8", errors="replace"
    )
    missing = []
    lines = text.splitlines()
    for position, line in enumerate(lines):
        if not line.startswith("--- "):
            continue
        match = _PATH_RE.match(line)
        if not match:
            continue
        path = match.group(1).strip()
        if path == "/dev/null" or path.startswith(_PRUNED_PREFIXES):
            continue
        # A rename/creation shows the new path on the following +++ line.
        following = lines[position + 1] if position + 1 < len(lines) else ""
        if following.startswith("+++ /dev/null"):
            continue  # deletion; the file is gone by design
        if not (_VENDORED / path).exists():
            missing.append(path)

    assert not missing, (
        "%s patches %s, which do not exist in the vendored tree. Either the "
        "patch is stale against the pin, or the file was pruned and the patch "
        "should not target it."
        % (patch.name, sorted(set(missing))[:3])
    )
