"""Parsing and file-IO coverage for MAC's dotenv helpers (``mac.deploy_env``)."""

from __future__ import annotations

import pytest

from mac import deploy_env


def test_env_assignment_parser_fallbacks_and_file_io(tmp_path) -> None:
    assert deploy_env._raw_env_assignment("missing") is None
    assert deploy_env._raw_env_assignment("export KEY=value") == ("KEY", "value")
    assert deploy_env._parse_env_assignment("KEY='unterminated") is None
    assert deploy_env._parse_env_assignment("KEY=value extra") == ("KEY", "value")
    assert deploy_env._parse_env_assignment("export KEY='a b'") == ("KEY", "a b")
    assert deploy_env._parse_env_assignment("export") is None
    assert deploy_env.read_env_file(tmp_path / "missing") == {}
    path = tmp_path / "env"
    deploy_env.write_env_file(path, {"SAFE": "value", "QUOTED": "a b"})
    assert deploy_env.read_env_file(path) == {"SAFE": "value", "QUOTED": "a b"}
    assert path.stat().st_mode & 0o777 == 0o600
    assert path.read_text(encoding="utf-8").startswith("# Generated by mac.\n")


def test_update_env_file_merges_without_dropping_existing_keys(tmp_path) -> None:
    path = tmp_path / "mac.env"
    deploy_env.write_env_file(path, {"KEEP": "1", "CHANGE": "old"})

    merged = deploy_env.update_env_file(path, {"CHANGE": "new", "ADD": 2})

    assert merged == {"KEEP": "1", "CHANGE": "new", "ADD": "2"}
    assert deploy_env.read_env_file(path) == merged
    assert path.stat().st_mode & 0o777 == 0o600


def test_worker_capabilities_dedupe_and_default_when_empty() -> None:
    assert deploy_env.normalize_worker_capabilities("") == deploy_env.DEFAULT_WORKER_CAPABILITIES
    assert deploy_env.normalize_worker_capabilities("ops, hermes,ops") == "ops,hermes"


def test_worker_capabilities_reject_the_retired_human_interface() -> None:
    retired = deploy_env.RETIRED_HUMAN_INTERFACE
    with pytest.raises(ValueError, match="Hermes is the only human interface"):
        deploy_env.normalize_worker_capabilities("ops,%s" % retired.upper())


def test_chat_gateway_implementation_rejects_the_retired_runtime() -> None:
    retired = deploy_env.RETIRED_HUMAN_INTERFACE
    with pytest.raises(ValueError, match="MAC_CHAT_GATEWAY_IMPL"):
        deploy_env.chat_gateway_implementation({"MAC_CHAT_GATEWAY_IMPL": " %s " % retired})
    assert deploy_env.chat_gateway_implementation({"MAC_CHAT_GATEWAY_IMPL": " Hermes "}) == "hermes"
    assert deploy_env.chat_gateway_implementation({}) == ""


def test_fleet_registry_rejects_a_retired_runtime_defaults_block() -> None:
    from mac.hermes_config_surface import _fleet_hermes_defaults
    from mac.models import ValidationError

    retired = deploy_env.RETIRED_HUMAN_INTERFACE
    with pytest.raises(ValidationError, match="defaults.hermes"):
        _fleet_hermes_defaults({"defaults": {retired: {"env": {"A": "1"}}}})
    assert _fleet_hermes_defaults({"defaults": {"hermes": {"env": {"A": "1"}}}}) == {
        "env": {"A": "1"}
    }
