"""Generated CLI reference must not depend on the interpreter that made it.

Python 3.13 changed how argparse wraps a subcommand usage line: the trailing
"..." after a long {choice,...} group moved onto the same line. The committed
docs/reference/cli.md is generated by CI on 3.11, so on 3.13+ the contract
gate's own fail-fast preflight reported it stale and refused to run a single
test -- and regenerating "to fix it" committed churn that then failed CI on
3.11. That cost time three times in one session.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _generator():
    spec = importlib.util.spec_from_file_location(
        "generate_docs_reference", ROOT / "scripts" / "generate-docs-reference.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_the_usage_tail_is_joined_onto_the_choices_line():
    """Canonical form is JOINED, and the direction matters.

    argparse already joins "..." onto the choices line whenever it fits, on
    every version -- so short groups (e.g. `mac rollout`) are identical
    everywhere and must not be touched. Only long groups differ. Splitting
    would have rewritten the short groups that were never broken; joining
    converges both.
    """
    generator = _generator()
    legacy = (
        "usage: mac task [-h]\n"
        "                {create,list,show}\n"
        "                ...\n"
        "\n"
        "positional arguments:"
    )
    modern = "usage: mac task [-h]\n                {create,list,show} ...\n\npositional arguments:"
    assert generator._normalize_usage(legacy) == modern
    # Idempotent: already-canonical text is unchanged.
    assert generator._normalize_usage(modern) == modern


def test_a_short_choices_group_is_never_split():
    """The regression the first attempt at this fix introduced."""
    generator = _generator()
    short = "                   {create,list,advance,health,rescue} ..."
    assert generator._normalize_usage(short) == short


def test_normalisation_leaves_unrelated_lines_alone():
    generator = _generator()
    for line in (
        "  --db DB    direct PostgreSQL control-plane authority",
        "positional arguments:",
        "    list                list tasks",
        "usage: mac [-h] [--db DB]",
    ):
        assert generator._normalize_usage(line) == line


def test_a_choices_group_without_a_tail_is_untouched():
    """A choices line with no following "..." must not absorb the next line."""
    generator = _generator()
    text = "                {create,list,show}\n\npositional arguments:"
    assert generator._normalize_usage(text) == text
