"""Deployment environment modeling.

This module is intentionally dependency-free. ``deploy/deploy-mac-fleet.sh``
imports it immediately after unpacking the source tree, before the mac package
or deploy venv exists.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import argparse
import os
import re
import secrets
import sys
import urllib.parse
from typing import Dict, Mapping, MutableMapping, Optional, Sequence

from mac.providers import ROUTER_PROVIDERS, router_secret_name


DEFAULT_WORKER_CAPABILITIES = (
    "ops,python,hermes,review,web_search,web_extract,web_crawl,firecrawl"
)


PROVIDERS = tuple(ROUTER_PROVIDERS)


ROUTER_KEYS = (
    "MAC_ROUTER_BACKEND",
    "MAC_ROUTER_PROVIDERS",
    "MAC_ROUTER_DEFAULT_MODEL",
    "MAC_ROUTER_WILDCARD_MODELS",
    "MAC_ROUTER_IMAGE_UPSTREAM",
    "MAC_ROUTER_IMAGE_KEY",
    "MAC_ROUTER_IMAGE_TIMEOUT",
)

GATEWAY_ROUTING_KEYS = (
    "OPENAI_BASE_URL",
    "OPENAI_API_KEY",
    "CUSTOM_BASE_URL",
    "MAC_HERMES_GATEWAY_BASE_URL",
    "MAC_HERMES_GATEWAY_API_KEY",
    "ACC_HERMES_GATEWAY_BASE_URL",
    "ACC_HERMES_GATEWAY_API_KEY",
)

UPSTREAM_PROVIDER_KEYS = tuple(
    dict.fromkeys(
        [
            *(provider.key_env for provider in PROVIDERS),
            *(provider.base_env for provider in PROVIDERS),
            "NVIDIA_API_BASE",
            "PERPLEXITY_API_BASE",
            "NVIDIA_IMAGE_BASE_URL",
            "FAL_KEY",
            "VLLM_API_KEY",
            "HAIMAKER_API_KEY",
            "LLM_KEY",
            "LLM_URL",
        ]
    )
)

INPROC_MANAGED_KEYS = tuple(dict.fromkeys([*ROUTER_KEYS, *GATEWAY_ROUTING_KEYS, *UPSTREAM_PROVIDER_KEYS]))


def build_router_provider_spec(provider_env_values: Mapping[str, str]) -> str:
    """Build ``MAC_ROUTER_PROVIDERS`` from provider keys collected by setup."""
    specs = []
    for priority, provider in enumerate(PROVIDERS):
        if provider.key_env not in provider_env_values:
            continue
        base_url = provider_env_values.get(provider.base_env) or provider.default_base_url
        specs.append(
            "%s=%s,%d,key=secret:%s"
            % (provider.id, base_url, priority, router_secret_name(provider.id))
        )
    return ";".join(specs)


@dataclass(frozen=True)
class DeployEnvConfig:
    env_file: Path
    mac_home: Path
    home: Path
    port: str
    home_channel: str
    gateway_model: str
    gateway_provider: str
    gateway_base_url: str
    hub_url: str
    hub_token: str
    bind_host: str
    worker_mode: str
    worker_capabilities: str
    worker_allowed_projects: str
    worker_required_metadata: str
    worker_require_canary: str
    agent: str
    supervisor_kind: str
    shared_services_manager: str
    qdrant_url: str
    qdrant_port: str
    firecrawl_url: str
    firecrawl_port: str
    network_provider: str
    fleet_name: str

    @property
    def is_hub(self) -> bool:
        return self.agent == self.shared_services_manager


def _unquote_env_value(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    return value


def parse_env_text(text: str) -> Dict[str, str]:
    values: Dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):]
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = _unquote_env_value(value)
    return values


def read_env_file(path: Path) -> Dict[str, str]:
    if not path.exists():
        return {}
    return parse_env_text(path.read_text(encoding="utf-8"))


_ENV_SAFE = re.compile(r"^[A-Za-z0-9_./:@=,+%-]*$")


def render_env(values: Mapping[str, str]) -> str:
    lines = [
        "# Generated by mac deploy/deploy-mac-fleet.sh.",
        "# Contains bearer tokens; keep mode 0600.",
    ]
    for key in sorted(values):
        rendered = str(values[key])
        if _ENV_SAFE.match(rendered):
            lines.append("%s=%s" % (key, rendered))
        else:
            lines.append("%s='%s'" % (key, rendered.replace("'", "'\\''")))
    return "\n".join(lines) + "\n"


def write_env_file(path: Path, values: Mapping[str, str]) -> None:
    path.write_text(render_env(values), encoding="utf-8")
    path.chmod(0o600)


def stable_id(prefix: str, value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", value.lower()).strip("_")
    return "%s_%s" % (prefix, safe or "default")


def _clear(values: MutableMapping[str, str], keys: Sequence[str]) -> None:
    for key in keys:
        values.pop(key, None)


def _service_url(
    *,
    configured_url: str,
    hub_url: str,
    configured_port: str,
    native_port: str,
) -> str:
    if configured_url:
        return configured_url.rstrip("/")
    parsed = urllib.parse.urlsplit(hub_url or "http://127.0.0.1:8789")
    if not parsed.scheme or not parsed.hostname:
        return ""
    host = parsed.hostname
    if ":" in host and not host.startswith("["):
        host = "[%s]" % host
    service_port = int(configured_port)
    hub_port = parsed.port or int(native_port or "8789")
    if hub_port == int(native_port or "8789") + 10000:
        service_port += 10000
    return urllib.parse.urlunsplit((parsed.scheme, "%s:%s" % (host, service_port), "", "", ""))


def _mac_hub_url(cfg: DeployEnvConfig) -> str:
    if cfg.worker_mode == "loop" and cfg.agent == cfg.shared_services_manager:
        return "http://127.0.0.1:%s" % cfg.port
    if cfg.network_provider in {"tailscale", "headscale"} and cfg.hub_url:
        return cfg.hub_url.rstrip("/")
    return "http://127.0.0.1:18789"


def _apply_core_values(values: MutableMapping[str, str], cfg: DeployEnvConfig, env: Mapping[str, str]) -> None:
    values.setdefault("MAC_SECRET_KEY", secrets.token_urlsafe(48))
    values.setdefault("MAC_API_TOKEN", secrets.token_urlsafe(32))
    values["MAC_DB"] = str(cfg.mac_home / "mac.db")
    values["MAC_PORT"] = cfg.port
    values["MAC_BIND_HOST"] = cfg.bind_host
    values["MAC_HUB_URL"] = _mac_hub_url(cfg)
    values["MAC_SUPERVISOR_KIND"] = cfg.supervisor_kind
    values["HERMES_HOME"] = str(cfg.home / ".hermes")
    values["HERMES_DISABLE_LAZY_INSTALLS"] = "1"
    values["HERMES_REDACT_SECRETS"] = "true"
    values["ACC_DIR"] = str(cfg.home / ".acc")
    values["MAC_HERMES_AGENT_DIR"] = str(cfg.mac_home / "src" / "mac" / "src" / "mac" / "_hermes")
    values["MAC_HERMES_APPLY_SLACK_ACCOUNT_SHIM"] = "1"
    values["MAC_HERMES_APPLY_GATEWAY_RUNTIME_SHIM"] = "1"
    values["MAC_HERMES_STARTUP_CHECK"] = "1"
    values.setdefault("MAC_REQUIRE_HERMES_STARTUP_READY", "0")
    values["MAC_URL"] = values["MAC_HUB_URL"]
    values["MAC_FLEET_NAME"] = cfg.fleet_name
    values["MAC_FLEET_TENANT_ID"] = stable_id("tenant", cfg.fleet_name)
    values["MAC_AGENT_ID"] = stable_id("agent", cfg.agent)
    values["MAC_HERMES_PERSONA_ID"] = stable_id("persona", cfg.agent)
    values["MAC_HERMES_INSTANCE_ID"] = stable_id("hermes", cfg.agent)
    values["MAC_WORKER_HERMES_INSTANCE_ID"] = values["MAC_HERMES_INSTANCE_ID"]
    values["MAC_HERMES_RUNTIME_CONTEXT_FILE"] = str(cfg.home / ".hermes" / "mac-runtime-context.json")
    values["MAC_HERMES_RUNTIME_CONTEXT_MARKDOWN"] = str(cfg.home / ".hermes" / "mac-runtime-context.md")
    values["MAC_HERMES_RUNTIME_CONTEXT_REQUIRED"] = "1"
    values["MAC_HERMES_WORKSPACE"] = str(cfg.mac_home / "src" / "mac")
    values["MAC_PROJECT_CONTRACT_FILE"] = str(cfg.mac_home / "src" / "mac" / ".mac" / "project.yaml")
    values["MAC_SELF_UPDATE_REPO"] = str(cfg.mac_home / "src" / "mac")
    if cfg.gateway_model:
        values["MAC_HERMES_GATEWAY_MODEL"] = cfg.gateway_model
        values["ACC_HERMES_GATEWAY_MODEL"] = cfg.gateway_model
        values["HERMES_INFERENCE_MODEL"] = cfg.gateway_model
        values["ACC_LLM_MODEL"] = cfg.gateway_model
    if cfg.gateway_provider:
        values["MAC_HERMES_GATEWAY_PROVIDER"] = cfg.gateway_provider
        values["ACC_HERMES_GATEWAY_PROVIDER"] = cfg.gateway_provider
        values["HERMES_INFERENCE_PROVIDER"] = cfg.gateway_provider
    if cfg.gateway_base_url:
        values["MAC_HERMES_GATEWAY_BASE_URL"] = cfg.gateway_base_url
        values["ACC_HERMES_GATEWAY_BASE_URL"] = cfg.gateway_base_url
        values["CUSTOM_BASE_URL"] = cfg.gateway_base_url
        values["OPENAI_BASE_URL"] = cfg.gateway_base_url
    if cfg.worker_mode == "loop" and cfg.agent == cfg.shared_services_manager:
        values["MAC_WORKER_TOKEN"] = values["MAC_API_TOKEN"]
    elif cfg.hub_token:
        values["MAC_WORKER_TOKEN"] = cfg.hub_token
    else:
        values.setdefault("MAC_WORKER_TOKEN", values["MAC_API_TOKEN"])
    values["MAC_WORKER_AGENT_NAME"] = cfg.agent
    values["MAC_WORKER_HOSTNAME"] = cfg.agent
    values["MAC_WORKER_MODE"] = cfg.worker_mode
    values["MAC_WORKER_CAPABILITIES"] = cfg.worker_capabilities
    values["MAC_WORKER_REQUIRE_CANARY"] = cfg.worker_require_canary
    values["MAC_WORKER_ALLOWED_PROJECTS"] = cfg.worker_allowed_projects
    values["MAC_WORKER_REQUIRED_METADATA"] = cfg.worker_required_metadata
    values["MAC_SHARED_SERVICES_MANAGER_AGENT"] = cfg.shared_services_manager
    values["MAC_REQUIRE_QDRANT_MEMORY"] = "1"
    values["MAC_QDRANT_MEMORY_ROLE"] = "shared_level2"
    values["MAC_MEMORY_TOPOLOGY_FILE"] = str(cfg.home / ".hermes" / "mac-memory-topology.json")
    values["MAC_REQUIRE_FIRECRAWL"] = "1"


def _apply_shared_service_urls(values: MutableMapping[str, str], cfg: DeployEnvConfig) -> None:
    hub_url = values.get("MAC_HUB_URL") or cfg.hub_url or "http://127.0.0.1:8789"
    qdrant_url = _service_url(
        configured_url=cfg.qdrant_url,
        hub_url=hub_url,
        configured_port=cfg.qdrant_port or "6333",
        native_port=cfg.port or "8789",
    )
    if qdrant_url:
        values["QDRANT_URL"] = qdrant_url
        values["QDRANT_ADDRESS"] = qdrant_url
        values["QDRANT_FLEET_URL"] = qdrant_url
    firecrawl_url = _service_url(
        configured_url=cfg.firecrawl_url,
        hub_url=hub_url,
        configured_port=cfg.firecrawl_port or "3002",
        native_port=cfg.port or "8789",
    )
    if firecrawl_url:
        values["FIRECRAWL_API_URL"] = firecrawl_url
        values["FIRECRAWL_GATEWAY_URL"] = firecrawl_url
        values.setdefault("FIRECRAWL_API_KEY", "none")
        values["MAC_WEB_SEARCH_PROVIDER"] = "firecrawl"
        values["MAC_WEB_SEARCH_URL"] = firecrawl_url
        values["HERMES_WEB_SEARCH_BACKEND"] = "firecrawl"
        values["HERMES_WEB_EXTRACT_BACKEND"] = "firecrawl"


def _deploy_router_config(env: Mapping[str, str]) -> Dict[str, str]:
    return {
        "backend": (env.get("MAC_DEPLOY_ROUTER_BACKEND") or "").strip(),
        "providers": (env.get("MAC_DEPLOY_ROUTER_PROVIDERS") or "").strip(),
        "default_model": (env.get("MAC_DEPLOY_ROUTER_DEFAULT_MODEL") or "").strip(),
        "wildcard_models": (env.get("MAC_DEPLOY_ROUTER_WILDCARD_MODELS") or "").strip(),
    }


def _apply_inproc_router(values: MutableMapping[str, str], cfg: DeployEnvConfig, env: Mapping[str, str]) -> None:
    router = _deploy_router_config(env)
    _clear(values, INPROC_MANAGED_KEYS)
    if cfg.is_hub:
        values["MAC_ROUTER_BACKEND"] = router["backend"]
        if router["default_model"]:
            values["MAC_ROUTER_DEFAULT_MODEL"] = router["default_model"]
        if router["wildcard_models"]:
            values["MAC_ROUTER_WILDCARD_MODELS"] = router["wildcard_models"]
        if router["providers"]:
            values["MAC_ROUTER_PROVIDERS"] = router["providers"]
            local_router_v1 = "http://127.0.0.1:%s/v1" % cfg.port
            values["OPENAI_BASE_URL"] = local_router_v1
            values["CUSTOM_BASE_URL"] = local_router_v1
            values["MAC_HERMES_GATEWAY_BASE_URL"] = local_router_v1
            values["ACC_HERMES_GATEWAY_BASE_URL"] = local_router_v1
            local_token = values.get("MAC_API_TOKEN") or ""
            if local_token:
                values["OPENAI_API_KEY"] = local_token
                values["MAC_HERMES_GATEWAY_API_KEY"] = local_token
                values["ACC_HERMES_GATEWAY_API_KEY"] = local_token
        if (env.get("NVIDIA_API_KEY") or "").strip():
            values["MAC_ROUTER_IMAGE_UPSTREAM"] = (
                env.get("MAC_DEPLOY_ROUTER_IMAGE_UPSTREAM") or "https://ai.api.nvidia.com/v1/genai"
            )
            values["MAC_ROUTER_IMAGE_KEY"] = "secret:nvidia-image"
        return

    hub_base = (values.get("MAC_HUB_URL") or cfg.hub_url or "").rstrip("/")
    local_token = values.get("MAC_API_TOKEN") or ""
    hub_token = cfg.hub_token or values.get("MAC_WORKER_TOKEN") or ""
    if hub_token and hub_token == local_token:
        hub_token = ""
    if not hub_base or not hub_token:
        return
    hub_v1 = "%s/v1" % hub_base
    values["OPENAI_BASE_URL"] = hub_v1
    values["CUSTOM_BASE_URL"] = hub_v1
    values["MAC_HERMES_GATEWAY_BASE_URL"] = hub_v1
    values["ACC_HERMES_GATEWAY_BASE_URL"] = hub_v1
    values["OPENAI_API_KEY"] = hub_token
    values["MAC_HERMES_GATEWAY_API_KEY"] = hub_token
    values["ACC_HERMES_GATEWAY_API_KEY"] = hub_token
    values["NVIDIA_API_KEY"] = hub_token
    values["NVIDIA_IMAGE_BASE_URL"] = "%s/v1/genai" % hub_base


def _apply_non_inproc_router(values: MutableMapping[str, str], env: Mapping[str, str]) -> None:
    router = _deploy_router_config(env)
    if router["backend"]:
        values["MAC_ROUTER_BACKEND"] = router["backend"]
    if router["providers"]:
        values["MAC_ROUTER_PROVIDERS"] = router["providers"]
    if router["default_model"]:
        values["MAC_ROUTER_DEFAULT_MODEL"] = router["default_model"]
    if router["wildcard_models"]:
        values["MAC_ROUTER_WILDCARD_MODELS"] = router["wildcard_models"]


def _apply_router(values: MutableMapping[str, str], cfg: DeployEnvConfig, env: Mapping[str, str]) -> None:
    backend = (env.get("MAC_DEPLOY_ROUTER_BACKEND") or "").strip()
    if backend.lower() == "inproc":
        _apply_inproc_router(values, cfg, env)
    else:
        _apply_non_inproc_router(values, env)


def _apply_home_channel(values: MutableMapping[str, str], cfg: DeployEnvConfig) -> None:
    home_channel = (
        cfg.home_channel
        or values.get("MAC_HERMES_SLACK_HOME_CHANNEL_NAME", "").strip().lstrip("#")
        or values.get("ACC_SLACK_HOME_CHANNEL_NAME", "").strip().lstrip("#")
        or values.get("SLACK_HOME_CHANNEL_NAME", "").strip().lstrip("#")
        or ""
    )
    values["MAC_HERMES_SLACK_HOME_CHANNEL_NAME"] = home_channel
    values["ACC_HERMES_SLACK_HOME_CHANNEL_NAME"] = home_channel
    values["SLACK_HOME_CHANNEL_NAME"] = home_channel
    values.setdefault("MAC_HERMES_SYNC_SLACK_HOME_CHANNELS", "1")
    values.setdefault("SLACK_ALLOWED_USERS", "*")
    values.setdefault("SLACK_REQUIRE_MENTION", "true")
    values.setdefault("SLACK_STRICT_MENTION", "true")


def build_mac_env(
    existing: Mapping[str, str],
    cfg: DeployEnvConfig,
    *,
    environ: Optional[Mapping[str, str]] = None,
) -> Dict[str, str]:
    env = os.environ if environ is None else environ
    values: Dict[str, str] = dict(existing)
    _apply_core_values(values, cfg, env)
    _apply_shared_service_urls(values, cfg)
    memory_model = (env.get("MAC_DEPLOY_MEMORY_EMBED_MODEL") or "").strip()
    if memory_model:
        values["MAC_MEMORY_EMBED_MODEL"] = memory_model
    values.setdefault("MAC_WORKER_WORKSPACE", str(cfg.mac_home / "agent-workspaces"))
    values.setdefault("MAC_WORKER_HEARTBEAT_INTERVAL", "30")
    values.setdefault("MAC_WORKER_POLL_INTERVAL", "2")
    values.setdefault("MAC_WORKER_LEASE_SECONDS", "900")
    values.setdefault("MAC_WORKER_EXECUTOR", str(cfg.mac_home / "bin" / "mac-hermes-task-executor"))
    values.setdefault("MAC_AGENT_STARTUP_SELF_TEST", "1")
    values.setdefault("MAC_AGENT_STARTUP_SELF_TEST_TIMEOUT", "120")
    values.setdefault("MAC_REVIEW_TICK_HUB_AGENT", cfg.shared_services_manager)
    _apply_router(values, cfg, env)
    _apply_home_channel(values, cfg)
    return values


def write_mac_env_file(
    cfg: DeployEnvConfig,
    *,
    environ: Optional[Mapping[str, str]] = None,
) -> Dict[str, str]:
    values = build_mac_env(read_env_file(cfg.env_file), cfg, environ=environ)
    write_env_file(cfg.env_file, values)
    return values


def config_from_legacy_args(args: Sequence[str], env: Mapping[str, str]) -> DeployEnvConfig:
    if len(args) != 25:
        raise SystemExit("write-mac-env expects 25 positional arguments; got %d" % len(args))
    gateway_model = args[5].strip()
    if gateway_model == "*":
        gateway_model = ""
    network_provider = (
        env.get("MAC_DEPLOY_NETWORK_PROVIDER")
        or env.get("NETWORK_PROVIDER")
        or "tailscale"
    ).strip().lower()
    return DeployEnvConfig(
        env_file=Path(args[0]),
        mac_home=Path(args[1]),
        home=Path(args[2]),
        port=args[3],
        home_channel=args[4].strip().lstrip("#"),
        gateway_model=gateway_model,
        gateway_provider=args[6].strip(),
        gateway_base_url=args[7].strip(),
        hub_url=args[8].strip(),
        hub_token=args[9].strip(),
        bind_host=args[10].strip() or "127.0.0.1",
        worker_mode=args[11].strip() or "heartbeat",
        worker_capabilities=args[12].strip() or DEFAULT_WORKER_CAPABILITIES,
        worker_allowed_projects=args[13].strip(),
        worker_required_metadata=args[14].strip(),
        worker_require_canary=args[15].strip() or "1",
        agent=args[16].strip(),
        supervisor_kind=args[17].strip(),
        shared_services_manager=args[18].strip() or args[16].strip(),
        qdrant_url=args[19].strip(),
        qdrant_port=args[21].strip() or "6333",
        firecrawl_url=args[22].strip(),
        firecrawl_port=args[24].strip() or "3002",
        network_provider=network_provider,
        fleet_name=env.get("FLEET_NAME") or "mac",
    )


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m mac.deploy_env")
    subparsers = parser.add_subparsers(dest="command", required=True)
    write_parser = subparsers.add_parser("write-mac-env")
    write_parser.add_argument("legacy_args", nargs=25)
    ns = parser.parse_args(argv)
    if ns.command == "write-mac-env":
        cfg = config_from_legacy_args(ns.legacy_args, os.environ)
        write_mac_env_file(cfg)
        return 0
    raise SystemExit("unknown command: %s" % ns.command)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
