"""Deployment environment modeling.

This module is intentionally dependency-free. ``deploy/deploy-mac-fleet.sh``
imports it immediately after unpacking the source tree, before the mac package
or deploy venv exists.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import argparse
import os
import re
import secrets
import shlex
import sys
import urllib.parse
from typing import Dict, Mapping, MutableMapping, Optional, Sequence

from mac.providers import ROUTER_PROVIDERS, router_secret_name, upstream_provider_env_vars


DEFAULT_WORKER_CAPABILITIES = (
    "ops,python,hermes,review,web_search,web_extract,web_crawl,firecrawl"
)


PROVIDERS = tuple(ROUTER_PROVIDERS)


ROUTER_KEYS = (
    "MAC_ROUTER_BACKEND",
    "MAC_ROUTER_PROVIDERS",
    "MAC_ROUTER_DEFAULT_MODEL",
    "MAC_ROUTER_WILDCARD_MODELS",
    "MAC_ROUTER_IMAGE_UPSTREAM",
    "MAC_ROUTER_IMAGE_KEY",
    "MAC_ROUTER_IMAGE_TIMEOUT",
)

GATEWAY_ROUTING_KEYS = (
    "OPENAI_BASE_URL",
    "OPENAI_API_KEY",
    "CUSTOM_BASE_URL",
    "MAC_HERMES_GATEWAY_BASE_URL",
    "MAC_HERMES_GATEWAY_API_KEY",
    "ACC_HERMES_GATEWAY_BASE_URL",
    "ACC_HERMES_GATEWAY_API_KEY",
)

UPSTREAM_PROVIDER_KEYS = tuple(upstream_provider_env_vars())

INPROC_MANAGED_KEYS = tuple(dict.fromkeys([*ROUTER_KEYS, *GATEWAY_ROUTING_KEYS, *UPSTREAM_PROVIDER_KEYS]))


def build_router_provider_spec(provider_env_values: Mapping[str, str]) -> str:
    """Build ``MAC_ROUTER_PROVIDERS`` from provider keys collected by setup."""
    specs = []
    for priority, provider in enumerate(PROVIDERS):
        if provider.key_env not in provider_env_values:
            continue
        base_url = provider_env_values.get(provider.base_env) or provider.default_base_url
        specs.append(
            "%s=%s,%d,key=secret:%s"
            % (provider.id, base_url, priority, router_secret_name(provider.id))
        )
    return ";".join(specs)


@dataclass(frozen=True)
class DeployPaths:
    env_file: Path
    mac_home: Path
    home: Path


@dataclass(frozen=True)
class ControlConfig:
    port: str
    hub_url: str
    hub_token: str
    bind_host: str
    supervisor_kind: str
    network_provider: str


@dataclass(frozen=True)
class GatewayConfig:
    home_channel: str
    model: str
    provider: str
    base_url: str


@dataclass(frozen=True)
class WorkerConfig:
    mode: str
    capabilities: str
    allowed_projects: str
    required_metadata: str
    require_canary: str


@dataclass(frozen=True)
class SharedServicesConfig:
    qdrant_url: str
    qdrant_port: str
    firecrawl_url: str
    firecrawl_port: str


@dataclass(frozen=True)
class DeployIdentity:
    agent: str
    shared_services_manager: str
    fleet_name: str

    @property
    def is_hub(self) -> bool:
        return self.agent == self.shared_services_manager


@dataclass(frozen=True)
class DeployEnvConfig:
    paths: DeployPaths
    control: ControlConfig
    gateway: GatewayConfig
    worker: WorkerConfig
    services: SharedServicesConfig
    identity: DeployIdentity

    @property
    def env_file(self) -> Path:
        return self.paths.env_file

    @property
    def mac_home(self) -> Path:
        return self.paths.mac_home

    @property
    def home(self) -> Path:
        return self.paths.home

    @property
    def port(self) -> str:
        return self.control.port

    @property
    def is_hub(self) -> bool:
        return self.identity.is_hub


def _parse_env_assignment(line: str) -> Optional[tuple[str, str]]:
    try:
        tokens = shlex.split(line, comments=False, posix=True)
    except ValueError:
        tokens = []
    if tokens:
        if tokens[0] == "export":
            tokens = tokens[1:]
        if tokens and "=" in tokens[0]:
            key, value = tokens[0].split("=", 1)
            return key.strip(), value

    if line.startswith("export "):
        line = line[len("export "):]
    if "=" not in line:
        return None
    key, value = line.split("=", 1)
    return key.strip(), value.strip()


def parse_env_text(text: str) -> Dict[str, str]:
    values: Dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        parsed = _parse_env_assignment(line)
        if parsed is None:
            continue
        key, value = parsed
        values[key] = value
    return values


def read_env_file(path: Path) -> Dict[str, str]:
    if not path.exists():
        return {}
    return parse_env_text(path.read_text(encoding="utf-8"))


_ENV_SAFE = re.compile(r"^[A-Za-z0-9_./:@=,+%-]*$")


def render_env(values: Mapping[str, str]) -> str:
    lines = [
        "# Generated by mac deploy/deploy-mac-fleet.sh.",
        "# Contains bearer tokens; keep mode 0600.",
    ]
    for key in sorted(values):
        rendered = str(values[key])
        if _ENV_SAFE.match(rendered):
            lines.append("%s=%s" % (key, rendered))
        else:
            lines.append("%s=%s" % (key, shlex.quote(rendered)))
    return "\n".join(lines) + "\n"


def write_env_file(path: Path, values: Mapping[str, str]) -> None:
    path.write_text(render_env(values), encoding="utf-8")
    path.chmod(0o600)


def stable_id(prefix: str, value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", value.lower()).strip("_")
    return "%s_%s" % (prefix, safe or "default")


def _clear(values: MutableMapping[str, str], keys: Sequence[str]) -> None:
    for key in keys:
        values.pop(key, None)


def _service_url(
    *,
    configured_url: str,
    hub_url: str,
    configured_port: str,
    native_port: str,
) -> str:
    if configured_url:
        return configured_url.rstrip("/")
    parsed = urllib.parse.urlsplit(hub_url or "http://127.0.0.1:8789")
    if not parsed.scheme or not parsed.hostname:
        return ""
    host = parsed.hostname
    if ":" in host and not host.startswith("["):
        host = "[%s]" % host
    service_port = int(configured_port)
    hub_port = parsed.port or int(native_port or "8789")
    if hub_port == int(native_port or "8789") + 10000:
        service_port += 10000
    return urllib.parse.urlunsplit((parsed.scheme, "%s:%s" % (host, service_port), "", "", ""))


def _mac_hub_url(cfg: DeployEnvConfig) -> str:
    if cfg.worker.mode == "loop" and cfg.identity.is_hub:
        return "http://127.0.0.1:%s" % cfg.control.port
    if cfg.control.network_provider in {"tailscale", "headscale"} and cfg.control.hub_url:
        return cfg.control.hub_url.rstrip("/")
    return "http://127.0.0.1:18789"


def _ensure_secret_values(values: MutableMapping[str, str]) -> None:
    values.setdefault("MAC_SECRET_KEY", secrets.token_urlsafe(48))
    values.setdefault("MAC_API_TOKEN", secrets.token_urlsafe(32))


def _path_values(cfg: DeployEnvConfig) -> Dict[str, str]:
    paths = cfg.paths
    hub_url = _mac_hub_url(cfg)
    return {
        "MAC_DB": str(paths.mac_home / "mac.db"),
        "MAC_PORT": cfg.control.port,
        "MAC_BIND_HOST": cfg.control.bind_host,
        "MAC_HUB_URL": hub_url,
        "MAC_URL": hub_url,
        "MAC_SUPERVISOR_KIND": cfg.control.supervisor_kind,
        "HERMES_HOME": str(paths.home / ".hermes"),
        "HERMES_DISABLE_LAZY_INSTALLS": "1",
        "HERMES_REDACT_SECRETS": "true",
        "ACC_DIR": str(paths.home / ".acc"),
        "MAC_HERMES_AGENT_DIR": str(paths.mac_home / "src" / "mac" / "src" / "mac" / "_hermes"),
        "MAC_HERMES_APPLY_SLACK_ACCOUNT_SHIM": "1",
        "MAC_HERMES_APPLY_GATEWAY_RUNTIME_SHIM": "1",
        "MAC_HERMES_STARTUP_CHECK": "1",
        "MAC_HERMES_RUNTIME_CONTEXT_FILE": str(paths.home / ".hermes" / "mac-runtime-context.json"),
        "MAC_HERMES_RUNTIME_CONTEXT_MARKDOWN": str(paths.home / ".hermes" / "mac-runtime-context.md"),
        "MAC_HERMES_RUNTIME_CONTEXT_REQUIRED": "1",
        "MAC_HERMES_WORKSPACE": str(paths.mac_home / "src" / "mac"),
        "MAC_PROJECT_CONTRACT_FILE": str(paths.mac_home / "src" / "mac" / ".mac" / "project.yaml"),
        "MAC_SELF_UPDATE_REPO": str(paths.mac_home / "src" / "mac"),
        "MAC_MEMORY_TOPOLOGY_FILE": str(paths.home / ".hermes" / "mac-memory-topology.json"),
    }


def _identity_values(cfg: DeployEnvConfig) -> Dict[str, str]:
    identity = cfg.identity
    hermes_id = stable_id("hermes", identity.agent)
    return {
        "MAC_FLEET_NAME": identity.fleet_name,
        "MAC_FLEET_TENANT_ID": stable_id("tenant", identity.fleet_name),
        "MAC_AGENT_ID": stable_id("agent", identity.agent),
        "MAC_HERMES_PERSONA_ID": stable_id("persona", identity.agent),
        "MAC_HERMES_INSTANCE_ID": hermes_id,
        "MAC_WORKER_HERMES_INSTANCE_ID": hermes_id,
        "MAC_SHARED_SERVICES_MANAGER_AGENT": identity.shared_services_manager,
    }


def _gateway_values(cfg: DeployEnvConfig) -> Dict[str, str]:
    gateway = cfg.gateway
    values: Dict[str, str] = {}
    if gateway.model:
        values.update(
            {
                "MAC_HERMES_GATEWAY_MODEL": gateway.model,
                "ACC_HERMES_GATEWAY_MODEL": gateway.model,
                "HERMES_INFERENCE_MODEL": gateway.model,
                "ACC_LLM_MODEL": gateway.model,
            }
        )
    if gateway.provider:
        values.update(
            {
                "MAC_HERMES_GATEWAY_PROVIDER": gateway.provider,
                "ACC_HERMES_GATEWAY_PROVIDER": gateway.provider,
                "HERMES_INFERENCE_PROVIDER": gateway.provider,
            }
        )
    if gateway.base_url:
        values.update(
            {
                "MAC_HERMES_GATEWAY_BASE_URL": gateway.base_url,
                "ACC_HERMES_GATEWAY_BASE_URL": gateway.base_url,
                "CUSTOM_BASE_URL": gateway.base_url,
                "OPENAI_BASE_URL": gateway.base_url,
            }
        )
    return values


def _worker_token(cfg: DeployEnvConfig, values: Mapping[str, str]) -> str:
    if cfg.worker.mode == "loop" and cfg.identity.is_hub:
        return values["MAC_API_TOKEN"]
    if cfg.control.hub_token:
        return cfg.control.hub_token
    return values.get("MAC_WORKER_TOKEN") or values["MAC_API_TOKEN"]


def _worker_values(cfg: DeployEnvConfig, values: Mapping[str, str]) -> Dict[str, str]:
    worker = cfg.worker
    identity = cfg.identity
    return {
        "MAC_WORKER_TOKEN": _worker_token(cfg, values),
        "MAC_WORKER_AGENT_NAME": identity.agent,
        "MAC_WORKER_HOSTNAME": identity.agent,
        "MAC_WORKER_MODE": worker.mode,
        "MAC_WORKER_CAPABILITIES": worker.capabilities,
        "MAC_WORKER_REQUIRE_CANARY": worker.require_canary,
        "MAC_WORKER_ALLOWED_PROJECTS": worker.allowed_projects,
        "MAC_WORKER_REQUIRED_METADATA": worker.required_metadata,
    }


def _shared_service_requirement_values() -> Dict[str, str]:
    return {
        "MAC_REQUIRE_QDRANT_MEMORY": "1",
        "MAC_QDRANT_MEMORY_ROLE": "shared_level2",
        "MAC_REQUIRE_FIRECRAWL": "1",
    }


def _shared_service_url_values(values: Mapping[str, str], cfg: DeployEnvConfig) -> Dict[str, str]:
    hub_url = values.get("MAC_HUB_URL") or cfg.control.hub_url or "http://127.0.0.1:8789"
    services = cfg.services
    out: Dict[str, str] = {}
    qdrant_url = _service_url(
        configured_url=services.qdrant_url,
        hub_url=hub_url,
        configured_port=services.qdrant_port or "6333",
        native_port=cfg.control.port or "8789",
    )
    if qdrant_url:
        out.update(
            {
                "QDRANT_URL": qdrant_url,
                "QDRANT_ADDRESS": qdrant_url,
                "QDRANT_FLEET_URL": qdrant_url,
            }
        )
    firecrawl_url = _service_url(
        configured_url=services.firecrawl_url,
        hub_url=hub_url,
        configured_port=services.firecrawl_port or "3002",
        native_port=cfg.control.port or "8789",
    )
    if firecrawl_url:
        out.update(
            {
                "FIRECRAWL_API_URL": firecrawl_url,
                "FIRECRAWL_GATEWAY_URL": firecrawl_url,
                "MAC_WEB_SEARCH_PROVIDER": "firecrawl",
                "MAC_WEB_SEARCH_URL": firecrawl_url,
                "HERMES_WEB_SEARCH_BACKEND": "firecrawl",
                "HERMES_WEB_EXTRACT_BACKEND": "firecrawl",
            }
        )
        if "FIRECRAWL_API_KEY" not in values:
            out["FIRECRAWL_API_KEY"] = "none"
    return out


def _deploy_router_config(env: Mapping[str, str]) -> Dict[str, str]:
    return {
        "backend": (env.get("MAC_DEPLOY_ROUTER_BACKEND") or "").strip(),
        "providers": (env.get("MAC_DEPLOY_ROUTER_PROVIDERS") or "").strip(),
        "default_model": (env.get("MAC_DEPLOY_ROUTER_DEFAULT_MODEL") or "").strip(),
        "wildcard_models": (env.get("MAC_DEPLOY_ROUTER_WILDCARD_MODELS") or "").strip(),
    }


def _apply_inproc_router(values: MutableMapping[str, str], cfg: DeployEnvConfig, env: Mapping[str, str]) -> None:
    router = _deploy_router_config(env)
    _clear(values, INPROC_MANAGED_KEYS)
    if cfg.is_hub:
        values["MAC_ROUTER_BACKEND"] = router["backend"]
        if router["default_model"]:
            values["MAC_ROUTER_DEFAULT_MODEL"] = router["default_model"]
        if router["wildcard_models"]:
            values["MAC_ROUTER_WILDCARD_MODELS"] = router["wildcard_models"]
        if router["providers"]:
            values["MAC_ROUTER_PROVIDERS"] = router["providers"]
            local_router_v1 = "http://127.0.0.1:%s/v1" % cfg.control.port
            values["OPENAI_BASE_URL"] = local_router_v1
            values["CUSTOM_BASE_URL"] = local_router_v1
            values["MAC_HERMES_GATEWAY_BASE_URL"] = local_router_v1
            values["ACC_HERMES_GATEWAY_BASE_URL"] = local_router_v1
            local_token = values.get("MAC_API_TOKEN") or ""
            if local_token:
                values["OPENAI_API_KEY"] = local_token
                values["MAC_HERMES_GATEWAY_API_KEY"] = local_token
                values["ACC_HERMES_GATEWAY_API_KEY"] = local_token
        if (env.get("NVIDIA_API_KEY") or "").strip():
            values["MAC_ROUTER_IMAGE_UPSTREAM"] = (
                env.get("MAC_DEPLOY_ROUTER_IMAGE_UPSTREAM") or "https://ai.api.nvidia.com/v1/genai"
            )
            values["MAC_ROUTER_IMAGE_KEY"] = "secret:nvidia-image"
        return

    hub_base = (values.get("MAC_HUB_URL") or cfg.control.hub_url or "").rstrip("/")
    local_token = values.get("MAC_API_TOKEN") or ""
    hub_token = cfg.control.hub_token or values.get("MAC_WORKER_TOKEN") or ""
    if hub_token and hub_token == local_token:
        hub_token = ""
    if not hub_base or not hub_token:
        return
    hub_v1 = "%s/v1" % hub_base
    values["OPENAI_BASE_URL"] = hub_v1
    values["CUSTOM_BASE_URL"] = hub_v1
    values["MAC_HERMES_GATEWAY_BASE_URL"] = hub_v1
    values["ACC_HERMES_GATEWAY_BASE_URL"] = hub_v1
    values["OPENAI_API_KEY"] = hub_token
    values["MAC_HERMES_GATEWAY_API_KEY"] = hub_token
    values["ACC_HERMES_GATEWAY_API_KEY"] = hub_token
    values["NVIDIA_API_KEY"] = hub_token
    values["NVIDIA_IMAGE_BASE_URL"] = "%s/v1/genai" % hub_base


def _apply_non_inproc_router(values: MutableMapping[str, str], env: Mapping[str, str]) -> None:
    router = _deploy_router_config(env)
    if router["backend"]:
        values["MAC_ROUTER_BACKEND"] = router["backend"]
    if router["providers"]:
        values["MAC_ROUTER_PROVIDERS"] = router["providers"]
    if router["default_model"]:
        values["MAC_ROUTER_DEFAULT_MODEL"] = router["default_model"]
    if router["wildcard_models"]:
        values["MAC_ROUTER_WILDCARD_MODELS"] = router["wildcard_models"]


def _apply_router(values: MutableMapping[str, str], cfg: DeployEnvConfig, env: Mapping[str, str]) -> None:
    backend = (env.get("MAC_DEPLOY_ROUTER_BACKEND") or "").strip()
    if backend.lower() == "inproc":
        _apply_inproc_router(values, cfg, env)
    else:
        _apply_non_inproc_router(values, env)


def _apply_home_channel(values: MutableMapping[str, str], cfg: DeployEnvConfig) -> None:
    home_channel = (
        cfg.gateway.home_channel
        or values.get("MAC_HERMES_SLACK_HOME_CHANNEL_NAME", "").strip().lstrip("#")
        or values.get("ACC_SLACK_HOME_CHANNEL_NAME", "").strip().lstrip("#")
        or values.get("SLACK_HOME_CHANNEL_NAME", "").strip().lstrip("#")
        or ""
    )
    values["MAC_HERMES_SLACK_HOME_CHANNEL_NAME"] = home_channel
    values["ACC_HERMES_SLACK_HOME_CHANNEL_NAME"] = home_channel
    values["SLACK_HOME_CHANNEL_NAME"] = home_channel
    values.setdefault("MAC_HERMES_SYNC_SLACK_HOME_CHANNELS", "1")
    values.setdefault("SLACK_ALLOWED_USERS", "*")
    values.setdefault("SLACK_REQUIRE_MENTION", "true")
    values.setdefault("SLACK_STRICT_MENTION", "true")


def build_mac_env(
    existing: Mapping[str, str],
    cfg: DeployEnvConfig,
    *,
    environ: Optional[Mapping[str, str]] = None,
) -> Dict[str, str]:
    env = os.environ if environ is None else environ
    values: Dict[str, str] = dict(existing)
    _ensure_secret_values(values)
    values.update(_path_values(cfg))
    values.update(_identity_values(cfg))
    values.update(_gateway_values(cfg))
    values.update(_worker_values(cfg, values))
    values.update(_shared_service_requirement_values())
    values.update(_shared_service_url_values(values, cfg))
    memory_model = (env.get("MAC_DEPLOY_MEMORY_EMBED_MODEL") or "").strip()
    if memory_model:
        values["MAC_MEMORY_EMBED_MODEL"] = memory_model
    values.setdefault("MAC_REQUIRE_HERMES_STARTUP_READY", "0")
    values.setdefault("MAC_WORKER_WORKSPACE", str(cfg.paths.mac_home / "agent-workspaces"))
    values.setdefault("MAC_WORKER_HEARTBEAT_INTERVAL", "30")
    values.setdefault("MAC_WORKER_POLL_INTERVAL", "2")
    values.setdefault("MAC_WORKER_LEASE_SECONDS", "900")
    values.setdefault("MAC_WORKER_EXECUTOR", str(cfg.paths.mac_home / "bin" / "mac-hermes-task-executor"))
    values.setdefault("MAC_AGENT_STARTUP_SELF_TEST", "1")
    values.setdefault("MAC_AGENT_STARTUP_SELF_TEST_TIMEOUT", "120")
    values.setdefault("MAC_REVIEW_TICK_HUB_AGENT", cfg.identity.shared_services_manager)
    _apply_router(values, cfg, env)
    _apply_home_channel(values, cfg)
    return values


def write_mac_env_file(
    cfg: DeployEnvConfig,
    *,
    environ: Optional[Mapping[str, str]] = None,
) -> Dict[str, str]:
    values = build_mac_env(read_env_file(cfg.env_file), cfg, environ=environ)
    write_env_file(cfg.env_file, values)
    return values


def config_from_legacy_args(args: Sequence[str], env: Mapping[str, str]) -> DeployEnvConfig:
    if len(args) != 25:
        raise SystemExit("write-mac-env expects 25 positional arguments; got %d" % len(args))
    gateway_model = args[5].strip()
    if gateway_model == "*":
        gateway_model = ""
    network_provider = (
        env.get("MAC_DEPLOY_NETWORK_PROVIDER")
        or env.get("NETWORK_PROVIDER")
        or "tailscale"
    ).strip().lower()
    agent = args[16].strip()
    return DeployEnvConfig(
        paths=DeployPaths(
            env_file=Path(args[0]),
            mac_home=Path(args[1]),
            home=Path(args[2]),
        ),
        control=ControlConfig(
            port=args[3],
            hub_url=args[8].strip(),
            hub_token=args[9].strip(),
            bind_host=args[10].strip() or "127.0.0.1",
            supervisor_kind=args[17].strip(),
            network_provider=network_provider,
        ),
        gateway=GatewayConfig(
            home_channel=args[4].strip().lstrip("#"),
            model=gateway_model,
            provider=args[6].strip(),
            base_url=args[7].strip(),
        ),
        worker=WorkerConfig(
            mode=args[11].strip() or "heartbeat",
            capabilities=args[12].strip() or DEFAULT_WORKER_CAPABILITIES,
            allowed_projects=args[13].strip(),
            required_metadata=args[14].strip(),
            require_canary=args[15].strip() or "1",
        ),
        services=SharedServicesConfig(
            qdrant_url=args[19].strip(),
            qdrant_port=args[21].strip() or "6333",
            firecrawl_url=args[22].strip(),
            firecrawl_port=args[24].strip() or "3002",
        ),
        identity=DeployIdentity(
            agent=agent,
            shared_services_manager=args[18].strip() or agent,
            fleet_name=env.get("FLEET_NAME") or "mac",
        ),
    )


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m mac.deploy_env")
    subparsers = parser.add_subparsers(dest="command", required=True)
    write_parser = subparsers.add_parser("write-mac-env")
    write_parser.add_argument("legacy_args", nargs=25)
    ns = parser.parse_args(argv)
    if ns.command == "write-mac-env":
        cfg = config_from_legacy_args(ns.legacy_args, os.environ)
        write_mac_env_file(cfg)
        return 0
    raise SystemExit("unknown command: %s" % ns.command)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
