#!/usr/bin/env python3
"""Generate deterministic CLI and OpenAPI reference pages for the docs site."""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from mac.api import create_app  # noqa: E402
from mac.services import ControlPlane  # noqa: E402


CLI_OUTPUT = ROOT / "docs" / "reference" / "cli.md"
OPENAPI_OUTPUT = ROOT / "docs" / "reference" / "openapi.md"
INVENTORY_OUTPUT = ROOT / "docs" / "reference" / "documentation-inventory.md"
ARCHIVE_OUTPUT = ROOT / "docs" / "archive" / "index.md"


def _help(*parts: str) -> str:
    result = subprocess.run(
        [sys.executable, "-m", "mac.cli", *parts, "--help"],
        cwd=ROOT,
        env={
            "PATH": os.environ.get("PATH", ""),
            # Editable environments may point at another worktree. Generated
            # help must always import the source beside this generator.
            "PYTHONPATH": str(ROOT / "src"),
        },
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError("mac %s --help failed" % " ".join(parts))
    return _normalize_usage(result.stdout.rstrip())


# Python 3.13 changed how argparse wraps a subcommand usage line: the trailing
# "..." that follows a long {choice,choice,...} group moved onto the same line.
# The committed reference is generated by CI on 3.11, so on a newer interpreter
# `--check` reported the file stale, the gate's own fail-fast preflight refused
# to run a single test, and the obvious response -- regenerate -- committed
# churn that then failed CI on 3.11.
#
# Canonical form is the pre-3.13 shape: "..." on its own line, indented to
# match. Normalising here keeps the generated reference identical on every
# supported interpreter instead of encoding one of them into the repository.
_USAGE_CHOICES_ONLY = re.compile(r"^(?P<indent>\s+)(?P<choices>\{[^}]*\})$")
_USAGE_TAIL_ONLY = re.compile(r"^\s+\.\.\.$")


def _normalize_usage(text: str) -> str:
    """Render argparse usage identically on 3.11 through 3.14+.

    Canonical form is the trailing "..." JOINED onto the choices line. That
    direction is not arbitrary: argparse already joins them whenever they fit,
    on every version, so short groups like `mac admin rollout` are identical
    everywhere. Only LONG groups differ -- 3.11 wraps the "..." to its own
    line, 3.13+ keeps it attached -- so joining converges both, while splitting
    would have rewritten the short groups that were never broken.
    """

    lines = text.splitlines()
    out: list[str] = []
    index = 0
    while index < len(lines):
        line = lines[index]
        match = _USAGE_CHOICES_ONLY.match(line)
        if (
            match is not None
            and index + 1 < len(lines)
            and _USAGE_TAIL_ONLY.match(lines[index + 1])
        ):
            out.append("%s%s ..." % (match.group("indent"), match.group("choices")))
            index += 2
            continue
        out.append(line)
        index += 1
    return "\n".join(out)


def _commands_from_parser() -> tuple[str, ...]:
    """Top-level commands read from the parser itself.

    This function used to exist only as a regex over the ``{a,b,c}`` choices
    line in ``mac --help``. That coupled the generator to one particular
    rendering, and it broke the moment the help was rewritten to lead with the
    four first-class objects instead of a 55-name brace list -- a documentation
    generator failing because the thing it documents became easier to read.

    The parser is the source the help is rendered FROM, so reading it cannot
    drift from what is shown, and it still sees commands the help renders
    compactly. Aliases share a parser object, so each is listed once.
    """
    from mac.cli import build_parser

    parser = build_parser()
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            first_name_for: dict[int, str] = {}
            for name, sub in action.choices.items():
                first_name_for.setdefault(id(sub), name)
            return tuple(first_name_for.values())
    return ()


def _top_level_commands(root_help: str) -> tuple[str, ...]:
    commands = _commands_from_parser()
    if commands:
        return commands
    # Fallback for a caller holding only help text.
    match = re.search(r"^\s*\{([^}]+)\}\s*$", root_help, re.MULTILINE)
    if match is None:
        raise RuntimeError("could not discover top-level commands from mac --help")
    commands = tuple(part.strip() for part in match.group(1).split(",") if part.strip())
    if not commands:
        raise RuntimeError("mac --help exposed no top-level commands")
    return commands


def cli_reference() -> str:
    root_help = _help()
    commands = _top_level_commands(root_help)
    with ThreadPoolExecutor(max_workers=min(8, len(commands))) as executor:
        command_help = dict(zip(commands, executor.map(_help, commands)))
    sections = [
        "# Command-line reference",
        "",
        "This page is generated from the current parser. Do not edit it directly.",
        "The book uses executable `bash` blocks; reference usage is rendered as output.",
        "",
        "## mac",
        "",
        "```console",
        "$ mac --help",
        root_help,
        "```",
    ]
    for command in commands:
        sections.extend(
            (
                "",
                f"## mac {command}",
                "",
                "```console",
                f"$ mac {command} --help",
                command_help[command],
                "```",
            )
        )
    return "\n".join(sections) + "\n"


def openapi_reference() -> str:
    app = create_app(control_plane=ControlPlane.in_memory())
    schema = app.openapi()
    lines = [
        "# HTTP API reference",
        "",
        "This route index is generated from the current FastAPI OpenAPI schema.",
        "Use the schema exposed by a running hub at `/openapi.json` for complete",
        "request and response definitions.",
        "",
        "| Method | Path | Operation |",
        "|---|---|---|",
    ]
    for path, operations in sorted(schema.get("paths", {}).items()):
        for method, operation in sorted(operations.items()):
            if method.lower() not in {"delete", "get", "patch", "post", "put"}:
                continue
            summary = str(operation.get("summary") or operation.get("operationId") or "")
            lines.append(f"| `{method.upper()}` | `{path}` | {summary.replace('|', '&#124;')} |")
    return "\n".join(lines) + "\n"


def _title(path: Path) -> str:
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    match = re.search(r"^#\s+(.+?)\s*$", text, re.MULTILINE)
    return match.group(1).strip() if match else path.stem.replace("-", " ").title()


def _category(relative: Path) -> str:
    value = relative.as_posix()
    if value.startswith("book/"):
        return "book"
    if value.startswith("archive/") or value.startswith("superpowers/"):
        return "historical archive"
    if value.startswith("adr/"):
        return "architecture decision"
    if value.startswith("reference/"):
        return "generated reference"
    if any(token in value for token in ("runbook", "deployment", "onboarding", "cutover", "availability", "recovery")):
        return "runbook"
    if value == "index.md":
        return "landing page"
    return "supplemental reference"


# Point-in-time decks under docs/presentation/ are pinned artifacts, not part of
# the documentation tree this inventory classifies: each is scoped to one commit
# and is never revised. Inventorying them would (a) label a deck as a current
# operating contract, which is exactly what it is not, and (b) make every new
# deck directory report the committed inventory stale, so `docs-build --check`
# would fail until an unrelated generated file was regenerated. mkdocs.yml
# excludes the same directory from the published site.
_INVENTORY_EXCLUDED_ROOTS = ("presentation",)


def _is_excluded_from_inventory(relative: Path) -> bool:
    return relative.parts[:1] in {(root,) for root in _INVENTORY_EXCLUDED_ROOTS}


def documentation_inventory() -> str:
    docs_root = ROOT / "docs"
    expected = {INVENTORY_OUTPUT, ARCHIVE_OUTPUT}
    pages = sorted(
        {
            path
            for path in docs_root.rglob("*")
            if path.suffix in {".md", ".mdx"}
            and not _is_excluded_from_inventory(path.relative_to(docs_root))
        }
        | expected,
        key=lambda path: path.relative_to(docs_root).as_posix(),
    )
    lines = [
        "# Documentation inventory",
        "",
        "This generated inventory classifies every Markdown source included in the",
        "documentation tree. Book chapters are authoritative and executable. Runbooks",
        "and references describe production boundaries. Historical material is retained",
        "for provenance and is not a current operating contract.",
        "",
        "Published skills are listed too. They are not documentation: ADR 0023 renders",
        "them into every coding harness, so a stale skill is an instruction agents obey",
        "rather than a page nobody reads. Being in this inventory is what puts them",
        "inside the same drift machinery as docs/.",
        "",
        "| Category | Source | Title |",
        "|---|---|---|",
    ]
    for page in pages:
        relative = page.relative_to(docs_root)
        title = _title(page).replace("|", "&#124;")
        lines.append(f"| {_category(relative)} | `{relative.as_posix()}` | {title} |")
    for skill in sorted((ROOT / "skills").glob("*/SKILL.md"), key=lambda p: p.parent.name):
        relative = skill.relative_to(ROOT)
        title = _title(skill).replace("|", "&#124;")
        lines.append(f"| published skill | `{relative.as_posix()}` | {title} |")
    return "\n".join(lines) + "\n"


def archive_index() -> str:
    docs_root = ROOT / "docs"
    archived = sorted(
        [*(docs_root / "archive" / "field-notes").glob("*.md"), *(docs_root / "adr").glob("*.md")],
        key=lambda path: path.name,
    )
    lines = [
        "# Historical archive",
        "",
        "These field notes and architecture decisions explain how MAC reached its current",
        "contracts. They are evidence, not current instructions. Follow the numbered book",
        "and current runbooks for operational work. Old field-note URLs redirect here to",
        "their retained sources.",
        "",
        "## Archived records",
        "",
    ]
    for page in archived:
        relative = page.relative_to(docs_root)
        lines.append(f"- [{_title(page)}](../{relative.as_posix()}) — `{relative.as_posix()}`")
    return "\n".join(lines) + "\n"


def _check_or_write(path: Path, expected: str, *, write: bool) -> bool:
    if write:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
        return True
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    if actual != expected:
        # Say what to DO, not just that something is wrong. This failure is the
        # fail-fast preflight of the contract gate, so it is often the first
        # thing a contributor sees, and "stale" alone sent people to regenerate
        # blindly -- which used to commit interpreter-dependent churn.
        print(
            f"generated documentation is stale: {path.relative_to(ROOT)}\n"
            f"  regenerate with: python scripts/generate-docs-reference.py --write\n"
            f"  then commit {path.relative_to(ROOT)} with your change.\n"
            f"  (running Python {os.sys.version_info.major}.{os.sys.version_info.minor}; "
            f"generated output is normalised to be interpreter-independent, so a diff "
            f"here is a real content change, not an interpreter artefact.)",
            file=os.sys.stderr,
        )
        return False
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    outputs = (
        (CLI_OUTPUT, cli_reference()),
        (OPENAPI_OUTPUT, openapi_reference()),
        (ARCHIVE_OUTPUT, archive_index()),
        (INVENTORY_OUTPUT, documentation_inventory()),
    )
    return 0 if all(_check_or_write(path, content, write=args.write) for path, content in outputs) else 1


if __name__ == "__main__":
    raise SystemExit(main())
